name: Build and Test

on:
  push:
    branches: [ main ]  # Trigger on push to main branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # Use Ubuntu runner

    steps:
      - uses: actions/checkout@v3  # Checkout code

      - name: Install dependencies
        run: npm install  # Replace with your project's install command

      - name: Run tests
        run: npm test  # Replace with your test command
